## An Array of Sequences
Most of the discussion in this chapter applies to sequences in general, from the familiar list to the str and bytes types that are new in Python 3. <br>

Standard library selection of sequence types implemented in C...
-  Container sequences: list, tuple, collections.deque can hold items of different types. <br>
-  Flat sequences: str, bytes, bytearray, memoryview, array.array hold items of one type. <br>


Another way of grouping sequence types is by mutability. A mutable object can be changed after it is created, and an immutable object can’t:
-  Mutable sequences: list, bytearray, array.array, collections.deque, and memoryview. <br>
-  Immutable sequences: tuple, str, and bytes <br>



## List Comprehensions and Generator Expressions
For brevity, many Python programmers refer to list comprehensions as listcomps, and generator expressions as genexps.
Listcomps do everything the map and filter functions do, without the contortions of the functionally challenged Python lambda.

In [1]:
# without a listcomp
symbols = "$¢£¥€¤"
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

In [2]:
# with a listcomp
[ord(symbol) for symbol in "$¢£¥€¤"]

[36, 162, 163, 165, 8364, 164]

Syntax Tip: In Python code, line breaks are ignored inside pairs of [], {}, or (). So you can build multiline lists, listcomps, genexps, dictionaries and the like without using the ugly \ line continuation escape.

In [5]:
# comparing a listcomp and a map / filter composition
[ord(s) for s in "$¢£¥€¤" if ord(s) > 127]          # ooh shiny

[162, 163, 165, 8364, 164]

In [7]:
list(filter(lambda c: c > 127, map(ord, "$¢£¥€¤"))) # yuck

[162, 163, 165, 8364, 164]

map and filter aren't necessarily faster than the associated listcomp either...

In [6]:
%timeit [ord(s) for s in "$¢£¥€¤" if ord(s) > 127]

1.59 µs ± 77 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
%timeit list(filter(lambda c: c > 127, map(ord, "$¢£¥€¤")))

1.92 µs ± 36 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Cartesian Products
The items that make up the cartesian product are tuples made from items from every input iterable.

In [13]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

In [14]:
# with list comps
tshirts = [(color, size) for color in colors for size in sizes]

tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [15]:
# with loops
tshirts = []
for color in colors:
    for size in sizes:
        tshirts.append((color, size))

tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

Listcomps are a one-trick pony: they build lists. To fill up other sequence types, a genexp is the way to go. The next section is a brief look at genexps in the context of building nonlist sequences.

## Generator Expressions
A genexp saves memory because it yields items one by one using the iterator protocol.

In [17]:
symbols = "$¢£¥€¤"

In [18]:
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [20]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [22]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

In [23]:
('%s %s' % (c, s) for c in colors for s in sizes)

<generator object <genexpr> at 0x0000000005030E60>

In [24]:
list(('%s %s' % (c, s) for c in colors for s in sizes))

['black S', 'black M', 'black L', 'white S', 'white M', 'white L']

## Tuples Are Not Just Immutable Lists
Tuples do double duty: they can be used as immutable lists and also as records with no field names.

In [31]:
my_list = [2, 4, 6, 8]
my_list[0]

2

In [33]:
my_list[0] = 0
my_list

[0, 4, 6, 8]

In [35]:
my_tuple = (2, 4, 6, 8)
my_tuple[0]

2

In [39]:
try:
    my_tuple[0] = 0
except Exception as e:
    print(e)

'tuple' object does not support item assignment


In [25]:
lax_coordinates = (33.9425, -118.408056)

In [26]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

In [27]:
city

'Tokyo'

In [28]:
area

8014

In [29]:
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

In [30]:
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


## Tuple Unpacking

In [41]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014) # as we saw earlier this example of tuple unpacking

The most visible form of tuple unpacking is parallel assignment; that is, assigning items from an iterable to a tuple of variables

In [42]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates

In [43]:
latitude

33.9425

In [44]:
longitude

-118.408056

An elegant application of tuple unpacking is swapping the values of variables without using a temporary variable

In [45]:
a, b = 2, 5
a, b

(2, 5)

In [46]:
b, a = a, b

In [47]:
a, b

(5, 2)

Another example of tuple unpacking is prefixing an argument with a star when calling a function

In [48]:
divmod(20, 8)

(2, 4)

In [49]:
t = (20, 8)

In [52]:
divmod(*t)

(2, 4)

In [53]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [55]:
import os
os.path.split('/home/luciano/.ssh/idrsa.pub')

('/home/luciano/.ssh', 'idrsa.pub')

In [56]:
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')

In [57]:
filename

'idrsa.pub'

Another way of focusing on just some of the items when unpacking a tuple is to use the *

In [60]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [61]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [62]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [63]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

Finally, a powerful feature of tuple unpacking is that it works with nested structures.

In [64]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))

                |   lat.    |   long.  


In [65]:
fmt = '{:15} | {:9.4f} | {:9.4f}'

In [66]:
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


## Named Tuples
The collections.namedtuple function is a factory that produces subclasses of tuple enhanced with field names and a class name - which helps debugging. Instances of a class that you build with namedtuple take exactly the same amount of memory as tuples because the field names are stored in the class. They use less memory than a regular object because they don’t store attributes in a per-instance __dict__.

In [70]:
import collections # as seen earlier
Card = collections.namedtuple('Card', ['rank', 'suit'])

In [72]:
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))

In [73]:
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [74]:
tokyo.population

36.933

In [75]:
tokyo.coordinates

(35.689722, 139.691667)

In [76]:
tokyo[1]

'JP'

In [77]:
City._fields

('name', 'country', 'population', 'coordinates')

In [79]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)

In [80]:
delhi._asdict()

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

-  _fields is a tuple with the field names of the class.
-  _make() allows you to instantiate a named tuple from an iterable
-  _asdict() returns a collections.OrderedDict built from the named tuple instance.

Now that we’ve explored the power of tuples as records, we can consider their second role as an immutable variant of the list type. tuple supports all list methods that do not involve adding or removing items, with one exception—tuple lacks the __reversed__ method.

## Slicing
In this section, we describe the use of these advanced forms of slicing...

In [1]:
my_list = [10, 20, 30, 40, 50, 60]

In [2]:
my_list[:2]

[10, 20]

In [3]:
my_list[2:]

[30, 40, 50, 60]

In [4]:
s = 'bicycle'

In [9]:
s[::3] # seq[start:stop:step]

'bye'

In [7]:
s[::-1]

'elcycib'

In [8]:
s[::-2]

'eccb'

## Assigning to Slices

In [1]:
l = list(range(10))

In [2]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l[2:5] = [20, 30]

In [4]:
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [5]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [7]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [9]:
# When the target of the assignment is a slice, the right side must be an iterable
# object, even if it has just one item.
try:
    l[2:5] = 100
except Exception as e:
    print(e)

can only assign an iterable


## Using + and * with Sequences

In [10]:
l = [1, 2, 3]

In [11]:
l * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

## Building Lists of Lists

In [13]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [14]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [19]:
# a tempting but wrong shortcut
weird_board = [['_'] * 3] * 3 # The outer list is made of three references to the same inner list.
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [20]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

## Augmented Assignment with Sequences
Here is a demonstration of *= with a mutable sequence and then an immutable one:

In [23]:
x = [1, 2, 3]
id(x)

81641800

In [24]:
x *= 2
x

[1, 2, 3, 1, 2, 3]

In [25]:
id(x) # after multiplication, the list is the same object, with new items appended

81641800

In [26]:
t = (1, 2, 3)
id(t)

82136448

In [27]:
t *= 2
t

(1, 2, 3, 1, 2, 3)

In [28]:
id(t) # after multiplication, a new tuple was created

81775016

Repeated concatenation of immutable sequences is inefficient, because instead of just appending new items, the interpreter has to copy the whole target sequence to create a new one with the new items concatenated.

## A += Assignment Puzzler

In [1]:
t = (1, 2, [30, 40])

In [2]:
try:
    t[2] += [50, 60]
except Exception as e:
    print(e)

'tuple' object does not support item assignment


In [3]:
t

(1, 2, [30, 40, 50, 60])

So we get both of:
* TypeError is raised with the message 'tuple' object does not support item assignment.
* t becomes (1, 2, [30, 40, 50, 60]).

This appears to be because the list can be changed (and is), but assignment to the tuple fails.
However, the tuple was originally referencing the memory address of this same list and so the underlying data for the tuple is changed whether we do assignment or not.

In [4]:
# we can do the same without an error (as we are working with a reference to the same list in the tuple)
t = (1, 2, [30, 40])
some_list = t[2]
some_list += [50, 60]
t

(1, 2, [30, 40, 50, 60])

This looks pretty cool: http://www.pythontutor.com/

## list.sort and the sorted Built-In Function
The list.sort method sorts a list in place - that is, without making a copy. <br>
In contrast, the built-in function sorted creates a new list and returns it.

In [3]:
import random

# Return a random integer N such that a <= N <= b
x = [random.randint(0, 10) for _ in range(5)]
x

[6, 1, 2, 2, 6]

In [7]:
result = list.sort(x)
result is None

True

In [8]:
x

[1, 2, 2, 6, 6]

In [9]:
result = sorted(x)
result

[1, 2, 2, 6, 6]

In [10]:
x = [random.randint(0, 10) for _ in range(1000000)]
%timeit list.sort(x)

14.5 ms ± 305 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
x = [random.randint(0, 10) for _ in range(1000000)]
%timeit sorted(x)

166 ms ± 4.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


If you just want to sort in place (and not chain) then list.sort is a faster option. The copy is time consuming.

Here are few examples from the book...

In [12]:
fruits = ['grape', 'raspberry', 'apple', 'banana']

In [13]:
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [14]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [15]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [16]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [17]:
fruits # sorted makes a copy, so fruits is unaffected

['grape', 'raspberry', 'apple', 'banana']

In [18]:
fruits.sort() # this is in place
fruits

['apple', 'banana', 'grape', 'raspberry']

Once your sequences are sorted, they can be very efficiently searched. Fortunately, the standard binary search algorithm is already provided in the bisect module of the Python standard library.

## Managing Ordered Sequences with bisect
bisect(haystack, needle) does a binary search for needle in haystack—which must be a sorted sequence—to locate the position where needle can be inserted while maintaining haystack in ascending order.

In [20]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d} {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * ' |'
        print(ROW_FMT.format(needle, position, offset))

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
        
    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)


DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14  | | | | | | | | | | | | | |31
30 @ 14  | | | | | | | | | | | | | |30
29 @ 13  | | | | | | | | | | | | |29
23 @ 11  | | | | | | | | | | |23
22 @  9  | | | | | | | | |22
10 @  5  | | | | |10
 8 @  5  | | | | |8 
 5 @  3  | | |5 
 2 @  1  |2 
 1 @  1  |1 
 0 @  0 0 


## Inserting with bisect.insort
Sorting is expensive, so once you have a sorted sequence, it’s good to keep it that way.

In [21]:
import bisect
import random

SIZE = 7
random.seed(0)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)


13 -> [13]
 6 -> [6, 13]
12 -> [6, 12, 13]
 6 -> [6, 6, 12, 13]
 0 -> [0, 6, 6, 12, 13]
 4 -> [0, 4, 6, 6, 12, 13]
 8 -> [0, 4, 6, 6, 8, 12, 13]


You can do this for your custom object if you implement the __lt__ method, because this is what bisect will use to compare your object.

In [27]:
import bisect
import random

class SomeClass(object):
    def __init__(self, value):
        self.value = value

    def __lt__(self, other):
        return self.value < other.value


my_list = []
for i in range(10):
    value = random.randint(0, 100)
    obj = SomeClass(value)
    bisect.insort(my_list, obj)


In [28]:
my_list

In [29]:
[obj.value for obj in my_list]

[12, 17, 18, 32, 39, 68, 77, 79, 90, 96]

## When a List Is Not the Answer
If you need to store 10 million floating-point values, an array is much more efficient, because an array does not actually hold full-fledged float objects, but only the packed bytes representing their machine values. On the other hand, if you are constantly adding and removing items from the ends of a list as a FIFO or LIFO data structure, a deque (double-ended queue) works faster.


## Arrays
If the list will only contain numbers, an array.array is more efficient than a list. A Python array is as lean as a C array. When creating an array, you provide a typecode, a letter to determine the underlying C type used to store each item in the array. For example, b is the typecode for signed char.

In [33]:
# https://docs.python.org/2/library/array.html
from array import array
from random import random

floats = array('d', (random() for i in range(10**6)))
floats[-1]

0.9843075818509196

In [34]:
with open('floats.bin', 'wb') as fp:
    floats.tofile(fp)


In [35]:
floats2 = array('d')
with open('floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10**6)

floats2[-1]

0.9843075818509196

In [36]:
floats2 == floats

True

And how do we sort them...

In [46]:
x = [random() for i in range(3)]

x = array("d", sorted(x))

x

array('d', [0.1863872967561484, 0.6693533884088415, 0.9993946893294476])

In [47]:
bisect.insort(x, 2.0)

In [48]:
x

array('d', [0.1863872967561484, 0.6693533884088415, 0.9993946893294476, 2.0])

## Memory Views
A memoryview is essentially a generalized NumPy array structure in Python itself (without the math). It allows you to share memory between data-structures (things like PIL images, SQLlite databases, NumPy arrays, etc.) without first copying. This is very important for large data sets.

In [51]:
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])

In [52]:
memv = memoryview(numbers)

In [53]:
len(memv)

5

In [54]:
memv[0]

-2

In [55]:
memv_oct = memv.cast('B')

In [56]:
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [57]:
memv_oct[5] = 4

In [58]:
numbers

array('h', [-2, -1, 1024, 1, 2])

## NumPy and SciPy

In [59]:
import numpy

a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
type(a)

numpy.ndarray

In [61]:
a.shape

(12,)

In [62]:
a.shape = 3, 4

In [63]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a[2]

array([ 8,  9, 10, 11])

In [65]:
a[2, 1]

9

In [66]:
a[:, 1]

array([1, 5, 9])

In [67]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Deques and Other Queues